/home/ec2-user/anaconda3/bin/python: can't open file 'run_squad.py': [Errno 2] No such file or directory
/home/ec2-user/anaconda3/bin/python: can't open file 'run_squad.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ec2-user/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ec2-user/anaconda3/bin/python', '-u', 'run_squad.py', '--local_rank=7', '--init_checkpoint=./results/checkpoints/ckpt_5030.pt', '--do_train', '--train_file=/fsx/DeepLearningExamples/PyTorch/LanguageModeling/BERT/data/download/squad/v1.1/train-v1.1.json', '--train_batch_size=4', '--do_predict', '--predict_file=/fsx/DeepLearningExamples/PyTorch/LanguageModeling/BERT/data/download/squad/v1.1/dev-v1.1.json', '--predict_batch_size=4', '--do_lower_case', '--bert_model=bert-large-uncased', '--learning_rate=3e-5', '--seed=1', '--num_train_epochs=2.0', '--max_seq_length=384', '--doc_stride=128', '--output_dir=./results/SQuAD', '--vocab_file=/fsx/DeepLearningExamples/PyTorch/LanguageModeling/BERT/data/download/google_pretrained_weights/uncased_L-24_H-1024_A-16/vocab.txt', '--config_file=bert_config.json', '--max_steps=-1']' returned non-zero exit status 2.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/ec2-user/anaconda3/bin/python: can't open file 'run_squad.py': [Errno 2] No such file or directory
/home/ec2-user/anaconda3/bin/python: can't open file 'run_squad.py': [Errno 2] No such file or directory
/home/ec2-user/anaconda3/bin/python: can't open file 'run_squad.py': [Errno 2] No such file or directory
/home/ec2-user/anaconda3/bin/python: can't open file 'run_squad.py': [Errno 2] No such file or directory
/home/ec2-user/anaconda3/bin/python: can't open file 'run_squad.py': [Errno 2] No such file or directory
/home/ec2-user/anaconda3/bin/python: can't open file 'run_squad.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/fsx/DeepLearningExamples/PyTorch/LanguageModeling/BERT/data/download/squad/v1.1/evaluate-v1.1.py", line 92, in <module>
    with open(args.prediction_file) as prediction_file:
FileNotFoundError: [Errno 2] No such file or directory: './results/SQuAD/predictions.json'
